### ISSUE TITLE
issue-1-see-car

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/driving-game#1]
## Feature
User can see their car.

## 💰 Motivation
The user needs to see what they will be controlling.

## 📐 Plan
Put a top-down image of a car on the page.

## ✅ Task List
- [x] Create the html outline and drop in the image of the car that will be used 
- [x] Style the car and user interface of the game using CSS
- [x] Ensure the user can see their car
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

## 🖼 Wireframes 
<img width="860" alt="Feature 1" src="https://user-images.githubusercontent.com/90408240/151883577-7a1b9965-9f75-44bb-8cd3-72efa5b28f93.png">
