### ISSUE TITLE
issue-6-obstacles

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/driving-game#11]
## Feature

User must dodge moving cars or the game will start over.

##💰 Motivation

Our game needs FUN ✌🏻

## 📐 Plan

Stop the game and create a crash pop-up when the user crashes into one of the obstacles, then restart the game. End the game when the user makes it to the finish line. 

## ✅ Task List

- [x]  Add enemy cars, finish line & crash images in html & position in starting positions in CSS
- [x] Ensure enemy car1 and the finish line are positioned from the left & bottom according to the screensize when user opens the game initially & define crash zone boundaries for all the edges
- [x] If the user drives off the screen, pop-up crash symbol, pause everything for a second and reset the game 
- [x] Create an object for the enemy cars & finish line that tracks each of their directions and positions
- [x] Create a checkCrash function that checks if the user's car crashes into enemy cars, if so, crash / reset the game
- [x] Create a function for the enemy cars that moves them (every 16 milliseconds for smooth movement) and turns them around when they reach the other side of the page, moving back the opposite direction
- [x] Create a win function that pops up "you win" clip art when user makes it to the finish line
- [x] Fix edge case when you hit an enemy car & the finish line at the same time, so you only crash (instead of crash & win)
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
