### ISSUE TITLE
issue-2-turn-car

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/driving-game#3]
## Feature 

User can turn their car.

## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create classes in CSS that change the car's direction when applied 
- [x] Create a data model that includes which way the car is facing (North, South, East, or West. Default=East)
- [x] Listen for 'keydown' event on the document 
   - [x] Change the direction the car is facing according to the data model depending on which key is pressed
   - [x] Reflect the directional changes with CSS classes so that the car changes directions in real time
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

## 🖼 Wireframes
![Feature2](https://user-images.githubusercontent.com/90408240/151909249-2615f810-5f50-472c-9615-a3e5378855cc.gif)
rames
