### ISSUE TITLE
issue-3-start-car

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/driving-game#5]
## Feature

User can start their car.

## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Change car to be absolutely positioned
- [x] Add a location to your data model to hold the car's x and y coordinates on the page (x = 0, y = 0)
- [x] Create startCar function that changes the style property of element objects to change car's top (x) and left(y) box offset styes
- [x]  Call the function with setInternval to move your car a few pixels every 16 milliseconds for a smooth movement. 
- [x] Ensure to update y location as car moves to the right 
- [x] Add inside event listener keydown function: if user presses space key, call the startCar function
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

## 🖼 Wireframes
![Feature 3](https://user-images.githubusercontent.com/90408240/151912477-f76b5595-d66b-4b9f-af0b-67abf14862a7.gif)
