### ISSUE TITLE
issue-4-stop-car

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/driving-game#7]
## Feature

User can stop their car.

## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to your data model to indicate whether or not the car is started (default = false)
- [x] Add line in the start car function that changes the value to true when the function is called 
- [x] Inside the if statement in the keydown eventlistener, while listening for spaces, check if the car.start is true, and if it is then call the clearInterval function to stop the car 
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

## 🖼 Wireframes 
![Feature 4](https://user-images.githubusercontent.com/90408240/151916882-3ac38bb0-0171-48f1-9002-69afe2586f82.gif)
