### ISSUE TITLE
issue-5-steer-car

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/driving-game#9]
## Feature

User can steer their car.

## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Check for the car's direction in the start car function and update the location in the right direction accordingly
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

## 🖼  Wireframes
![Feature 5](https://user-images.githubusercontent.com/90408240/151919056-8733a4c4-925f-4a6d-bcf5-c3c5a0e45621.gif)
